name: Deployment Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  deploy: 
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel previous redundant build
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          acces_token: ${{ github.token }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Installing Node.js enviroment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        #run: npm install --no-audit --no-fund --no-optional
        run: npm ci
      - name: Lint
        run: npm run eslint
      - name: E2E Test
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-test
          wait-on: http://localhost:8011
      - name: Deploy to Digital Ocean
        if: ${{ github.event_name == 'push' }}
        run: echo "Time to DO"
